name: Dify Scheduled Workflow

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（北京时间 08:00）
    - cron: '00 3 * * *'
    # 添加更多时间规则（每30分钟示例）：
    # - cron: '*/10 * * * *'

jobs:
  trigger-dify-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Dify Workflow
        env:
          DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
          WORKFLOW_URL: ${{ secrets.WORKFLOW_API_URL }}
        run: |
          # 使用 curl 调用 Dify API
          response=$(curl -s -X POST "$WORKFLOW_URL" \
            -H "Authorization: Bearer $DIFY_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {
                    "city": "310000",
                    "key": @{variables('weather_api_key')},
                    "output": "JSON",
                    "extensions": "all"
                },
                  "response_mode": "streaming",
                  "user": "abc-123"
                }')

          # 检查响应（可选）
          echo "API Response: $response"
          
          # 示例：检查响应是否包含错误
          if echo "$response" | grep -q '"error"'; then
            echo "Error in API response!"
            exit 1
          fi
